#!/bin/sh

set -eu

lb config noauto \
    --mode ubuntu \
    --distribution noble \
    --parent-distribution noble \
    --architectures amd64 \
    --linux-flavours generic \
    --linux-packages linux \
    --keyring-packages ubuntu-keyring \
    --archive-areas "main restricted universe multiverse" \
    --parent-archive-areas "main restricted universe multiverse" \
    --mirror-bootstrap "http://archive.ubuntu.com/ubuntu" \
    --mirror-chroot "http://archive.ubuntu.com/ubuntu" \
    --mirror-chroot-security "http://security.ubuntu.com/ubuntu" \
    --mirror-chroot-volatile "http://archive.ubuntu.com/ubuntu" \
    --mirror-binary "http://archive.ubuntu.com/ubuntu" \
    --mirror-binary-security "http://security.ubuntu.com/ubuntu" \
    --mirror-binary-volatile "http://archive.ubuntu.com/ubuntu" \
    --parent-mirror-bootstrap "http://archive.ubuntu.com/ubuntu" \
    --parent-mirror-chroot "http://archive.ubuntu.com/ubuntu" \
    --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu" \
    --parent-mirror-chroot-volatile "http://archive.ubuntu.com/ubuntu" \
    --parent-mirror-binary "http://archive.ubuntu.com/ubuntu" \
    --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu" \
    --parent-mirror-binary-volatile "http://archive.ubuntu.com/ubuntu" \
    --initramfs casper \
    --initsystem systemd \
    --binary-images iso-hybrid \
    --bootloader syslinux \
    --bootappend-live "boot=casper components quiet splash" \
    --debian-installer false \
    --firmware-chroot false \
    --firmware-binary false \
    --security true \
    --iso-application "Raven OS" \
    --iso-publisher "Raven OS Project" \
    --iso-volume "Raven_NOBLE" \
    "${@}"
